#!/bin/sh -eux

[ ! -e "${SNAP_COMMON}/caddy-mod.bkp" ] || {
  # Put the new caddy binary in "${SNAP_COMMON}"
  cp -f "${SNAP}/usr/bin/caddy" "${SNAP_COMMON}/caddy-mod"

  # Rebuild caddy with all prior modules
  snapctl get module | while read -r k v; do
    case $k in
      # Ignore the json braces
      \{|\}) ;;
      *) mod="$(echo "$v" | sed -e 's/"//g')"
         if ! "${SNAP_COMMON}/caddy-mod" add-package "$mod"; then
           mv -f "${SNAP_COMMON}/caddy-mod.bkp" "${SNAP_COMMON}/caddy-mod"
           # Bail on failure. Notify user.
           snapctl set update-failed=true
           break
      fi ;;
    esac
  # Don't cause refreshes to fail
  done || mv -f "${SNAP_COMMON}/caddy-mod.bkp" "${SNAP_COMMON}/caddy-mod"
}
